language: python
python:
    - "3.6"
install:
    # CODELINK: conda installation instructions per https://conda.io/docs/user-guide/tasks/use-conda-with-travis-ci.html
    - wget -O miniconda.sh https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    # Install MetagenomeScope from source
    - travis_retry conda create -q -c anaconda -n mgsc python=3.6 graphviz numpy
    - source activate mgsc
    - pip install -e .[dev]
    # Install npm packages needed for JS testing
    - npm install -g mocha-headless-chrome nyc
    # Install npm packages needed for JS style-checking
    - npm install -g prettier jshint
script:
    # This runs both the Python and JS tests
    - make test
    - make stylecheck
after_success:
    # This section based on Qurro's Makefile. Upload coverage info to Codecov.
    - wget -O codecov.sh https://codecov.io/bash
    - bash codecov.sh -c
